# Generated by Django 5.1.3 on 2025-10-24 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.choice')),
            ],
            options={
                'verbose_name': 'Blockchain Choice',
                'verbose_name_plural': 'Blockchain Choices',
            },
            bases=('polls.choice',),
        ),
        migrations.CreateModel(
            name='BlockchainQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.question')),
                ('blockchain_id', models.IntegerField(blank=True, help_text='Question ID on blockchain', null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Transaction hash of creation', max_length=66, null=True)),
                ('is_blockchain_synced', models.BooleanField(default=False, help_text='Is synced with blockchain')),
                ('use_blockchain', models.BooleanField(default=False, help_text='Use blockchain for this question')),
                ('blockchain_created_at', models.DateTimeField(blank=True, help_text='When created on blockchain', null=True)),
            ],
            options={
                'verbose_name': 'Blockchain Question',
                'verbose_name_plural': 'Blockchain Questions',
                'ordering': ['-pub_date'],
            },
            bases=('polls.question',),
        ),
        migrations.CreateModel(
            name='BlockchainVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_index', models.IntegerField()),
                ('voter_address', models.CharField(help_text='Ethereum wallet address', max_length=42)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.blockchainquestion')),
            ],
            options={
                'verbose_name': 'Blockchain Vote',
                'verbose_name_plural': 'Blockchain Votes',
                'ordering': ['-timestamp'],
                'unique_together': {('question', 'voter_address')},
            },
        ),
    ]
