# Generated by Django 6.0.1 on 2026-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_blockchainchoice_blockchainquestion_blockchainvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainvote",
            name="log_index",
            field=models.IntegerField(
                default=0, help_text="Event log index for idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainvote",
            index=models.Index(
                fields=["transaction_hash", "log_index"], name="tx_log_index_idx"
            ),
        ),
    ]
